---
- name: TELEGRAF CONFIG
  hosts: datacenter
  ignore_errors: no
  gather_facts: no
  vars:
    telegrafhost: localhost
    snmpv3_name: telegraf
    snmpv3_authprot: MD5
    snmpv3_authpw: N3tworklab
    snmpv3_privprot: AES
    snmpv3_privpw: N3tworklab

  tasks:
    - name: TEMPLATE OUT TELEGRAF.CONF FILES
      template:
        src: nexus.j2
        dest: /playbooks/telegraf.d/{{inventory_hostname}}_snmp.conf
      delegate_to: "{{ telegrafhost }}"
      #      notify: RELOAD TELEGRAF

    - name: READ LIST OF ALL TELEGRAF.CONF FILES IN DIRECTORY
      find:
        paths: /playbooks/telegraf.d/
        file_type: file
        recurse: no
        patterns: "*snmp.conf"
      delegate_to: "{{ telegrafhost }}"
      register: files_matched
      run_once: true

    - name: DELETE STALE TELEGRAF.CONF FILES
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_matched.files|flatten(levels=1) }}"
      loop_control:
        label: "{{ item.path }}"
      delegate_to: "{{ telegrafhost }}"
      when: (item.path | basename | regex_replace('_snmp.conf') not in ansible_play_hosts_all)
      notify: RELOAD TELEGRAF
      run_once: true

      #  handlers:

      #    - name: RELOAD TELEGRAF
      #shell: sudo systemctl reload telegraf
      #  delegate_to: "{{ telegrafhost }}"
      #  run_once: true
