---
nos: iosxe
hostname_config:
  hostname: csr1kv01
interfaces_config:
  ietf-interfaces:interfaces:
    interface:
    - enabled: true
      ietf-ip:ipv4: {}
      ietf-ip:ipv6: {}
      name: GigabitEthernet1
      type: iana-if-type:ethernetCsmacd
    - description: Internet Link-1 -- BIRD tenant
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.1.1
          netmask: 255.255.255.252
      ietf-ip:ipv6: {}
      name: GigabitEthernet1.100
      type: iana-if-type:ethernetCsmacd
    - description: Internet Link-1 -- PIG tenant
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.1.2.1
          netmask: 255.255.255.252
      ietf-ip:ipv6: {}
      name: GigabitEthernet1.200
      type: iana-if-type:ethernetCsmacd
    - enabled: false
      ietf-ip:ipv4: {}
      ietf-ip:ipv6: {}
      name: GigabitEthernet2
      type: iana-if-type:ethernetCsmacd
    - description: Internet Link-2 -- BIRD tenant
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.2.1.1
          netmask: 255.255.255.252
      ietf-ip:ipv6: {}
      name: GigabitEthernet2.100
      type: iana-if-type:ethernetCsmacd
    - description: Internet Link-2 -- PIG tenant
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.2.2.1
          netmask: 255.255.255.252
      ietf-ip:ipv6: {}
      name: GigabitEthernet2.200
      type: iana-if-type:ethernetCsmacd
    - enabled: false
      ietf-ip:ipv4: {}
      ietf-ip:ipv6: {}
      name: GigabitEthernet3
      type: iana-if-type:ethernetCsmacd
    - description: MANAGEMENT
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 10.255.255.200
          netmask: 255.255.255.128
      ietf-ip:ipv6: {}
      name: GigabitEthernet4
      type: iana-if-type:ethernetCsmacd
    - description: LOOPBACK/RID-DFLT
      enabled: true
      ietf-ip:ipv4:
        address:
        - ip: 100.100.100.100
          netmask: 255.255.255.255
      ietf-ip:ipv6: {}
      name: Loopback0
      type: iana-if-type:softwareLoopback
