---
- name:                                 Define global settings
  hosts:                                localhost
  connection:                           local
  gather_facts:                         no

  vars_files:
     - ./global-vars/apic-details.yaml

  vars_prompt:
     - name:                            vrfrun
       prompt:                          Please Choose your VRF to apply Default Leak Policy
       private:                         no

  tasks:
    - name:
      set_fact:
        desired_state:                  present
        vrfrun:                         "{{ vrfrun }}"
        vrffilepath:                    vars/000-GLOBAL-INFOS_{{ vrfrun }}.yaml
        
    - name:                             apic details
      set_fact:
        apic_info:                      &apic_info
          host:                         "{{ apic_info.host }}"
          username:                     "{{ apic_info.username }}"
          private_key:                  "{{ apic_info.private_key }}"
          certificate_name:             "{{ apic_info.certificate_name }}"
          validate_certs:               no

  tags:                                 always

- import_playbook:                      ./snapshot.yaml
  vars:
    snapshotDescription:                PRE- 009 L3OUT INSTANTIATION
  tags:                                 pre-snapshot


- name:                                 ASSOCIATE DEFAULT LEAK POLICY TO L3OUT
  hosts:                                localhost
  connection:                           local
  gather_facts:                         no

  pre_tasks:
    - name:                             INCLUDE SPECS L3OUT
      include_vars:                     "{{ vrffilepath }}"

  tasks:
    - name:                             DEFAULT LEAK POLICY CREATION/ASSOCIATION
      aci_rest:
          <<:                           *apic_info
          method:                       post
          path:                         '/api/mo/uni/tn-{{ item.tenant }}/out-{{ item.l3out_name }}/defrtleak.json'
          content:
            l3extDefaultRouteLeakP:
              attributes:
                always: 'no'
                annotation: 'orchestrator:ansible'
                criteria: 'in-addition'
                scope: 'l3-out'
      with_items:
        - "{{ l3out }}"

  tags:
    - l3out

- import_playbook:                      ./snapshot.yaml
  vars:
    snapshotDescription:                POST- 009 L3OUT INSTANTIATION
  tags:                                 post-snapshot

