{
 "title": "Cisco NXOS Switch SNMP Style",
 "description": "Device Dashboard via SNMPv3",
 "tags": [ "menu" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"agent_host\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "ifName",
    "label": "ifName",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"ifName\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Switch Infos",
   "type": "table",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Version\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\n  |> map(fn: (r) => ({ r with _value: r._value / 100 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield()\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU 1min",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CPU1m\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "CPU1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "round(($A * 100) / ($A + $B))", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "from(bucket: \"tigstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CPU1m\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\r\n",
     "select": [
      [
       { "params": [ "CPU1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "MemUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Mem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Supply States",
   "type": "gauge",
   "description": "PSU incl. Fabric Extender ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "agent_name" ], "type": "tag" }
     ],
     "measurement": "IF",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: -20s, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"FRU\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PSU_Status\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"n9kv01\" or r[\"agent_host\"] == \"n9kv02\" or r[\"agent_host\"] == \"n9kv03\" or r[\"agent_host\"] == \"n9kv04\" or r[\"agent_host\"] == \"n9kv11\" or r[\"agent_host\"] == \"n9kv12\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  |> group(columns: [\"PSU_Status\"])\n  |> sum(column: \"_value\")\n  |> group()\n",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ifOperStatus", "operator": "<", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "FAN Status",
   "type": "stat",
   "description": "FAN incl. Fabric Extender",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "agent_name" ], "type": "tag" }
     ],
     "measurement": "IF",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: -10s, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"FRU\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FAN_Status\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"n9kv01\" or r[\"agent_host\"] == \"n9kv02\" or r[\"agent_host\"] == \"n9kv03\" or r[\"agent_host\"] == \"n9kv04\" or r[\"agent_host\"] == \"n9kv11\" or r[\"agent_host\"] == \"n9kv12\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  |> group(columns: [\"FAN_Status\"])\n  |> sum(column: \"_value\")\n  |> group()\n  ",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ifOperStatus", "operator": "<", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MemUsed\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\r\n"
    }
   ]
  },
  {
   "title": "Syslog messages",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"appname\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> group()\n  "
    }
   ]
  },
  {
   "title": "Interface Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "ifName",
   "targets": [
    {}
   ]
  },
  {
   "title": "Interface $ifName Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "repeat": "ifName",
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IF",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInDiscards\" or r[\"_field\"] == \"ifInErrors\" or r[\"_field\"] == \"ifInUnknownProtos\" or r[\"_field\"] == \"ifOutDiscards\" or r[\"_field\"] == \"ifOutErrors\")\n  |> filter(fn: (r) => r[\"ifName\"] == \"${ifName}\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\n",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Bits_IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Bits_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Discards_IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Discards_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Errors_IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Errors_OUT" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "UnknownProto_IN" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=~", "value": "/^$ifName$/" },
      { "condition": "AND", "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface ${ifName} Current State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 790 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "ifAlias" ], "type": "tag" },
      { "params": [ "ifOperStatusCause" ], "type": "tag" }
     ],
     "measurement": "IF",
     "query": "from(bucket: \"tigstack\")\n  |> range(start: -20s, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifAdminStatus\" or r[\"_field\"] == \"ifHighSpeed\" or r[\"_field\"] == \"ifOperStatus\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"ifName\"] == \"${ifName}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AdminStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "OperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  }
 ]
}