{
 "title": "DME Nexus DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "nxos",
    "query": "\timport \"influxdata/influxdb/v1\"\r\n  v1.tagValues( bucket: v.bucket, tag: \"agent_host\", predicate: (r) => true, start: -1d )"
   },
   {
    "name": "ifName",
    "query": "\timport \"influxdata/influxdb/v1\"\r\n  v1.tagValues( bucket: v.bucket, tag: \"ifName\", predicate: (r) => true, start: -1d )"
   }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proc Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-NX-OS-device:System/procsys-items/sysload-items\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalProc\" or r[\"_field\"] == \"runProc\")\n  |> filter(fn: (r) => r[\"source\"] == \"${host}\")\n"
    }
   ]
  },
  {
   "title": "Load Average by Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-NX-OS-device:System/procsys-items/sysload-items\")\n  |> filter(fn: (r) => r[\"_field\"] == \"loadAverage15m\" or r[\"_field\"] == \"loadAverage1m\" or r[\"_field\"] == \"loadAverage5sec\" or r[\"_field\"] == \"loadAverage5m\")\n  |> filter(fn: (r) => r[\"source\"] == \"${host}\")"
    }
   ]
  },
  { "title": "Interface Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "${ifName} Packets In/Out Packets by Type",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"show interface counters detailed\")\n  |> filter(fn: (r) => r[\"source\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"TABLE_interface\"] == \"${ifName}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eth_inpkts\" or r[\"_field\"] == \"eth_outpkts\" or r[\"_field\"] == \"eth_inucast\" or r[\"_field\"] == \"eth_inmcast\" or r[\"_field\"] == \"eth_outucast\" or r[\"_field\"] == \"eth_outmcast\" or r[\"_field\"] == \"eth_outgiants\" or r[\"_field\"] == \"eth_ingiants\")\n"
    }
   ]
  },
  {
   "title": "Interface ${ifName} Transceiver details",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"tigstack\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"show interface transceiver detail\")\r\n  |> filter(fn: (r) => r[\"TABLE_interface\"] == \"${ifName}\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_power\" or r[\"_field\"] == \"tx_power\")\r\n"
    }
   ]
  }
 ]
}